name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # This triggers the workflow on version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install archive tools
      run: sudo apt install zip
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.repository.default_branch }}
    
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 8.6.1

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.x'
        cache: 'pnpm'
        cache-dependency-path: 'web/pnpm-lock.yaml'
    
    - name: Install script dependencies
      run: pnpm install
      working-directory: /

    - name: Install web dependencies
      run: pnpm install
      working-directory: web
    
    - name: Build Script
      run: pnpm run build
      working-directory: /

    - name: Build Svelte project
      run: pnpm run build
      working-directory: web

    - name: Bundle files
      run: |
        mkdir -p ./temp/bl_appearance
        mkdir -p ./temp/bl_appearance/dist/
        mkdir -p ./temp/bl_appearance/build/
        cp ./{LICENSE,README.md,fxmanifest.lua,appearance.sql,Installation.md} ./temp/bl_appearance
        cp -r ./{data,locales} ./temp/bl_appearance
        cp -r ./build ./temp/bl_appearance/build/
        cp -r ./dist ./temp/bl_appearance/dist/
        cd ./temp && zip -r ../bl_appearance.zip ./bl_appearance

    - name: Create Release
      uses: 'marvinpinto/action-automatic-releases@latest'
      with:
        repo_token: '${{ secrets.GITHUB_TOKEN }}'
        title: ${{ github.ref }}
        prerelease: false
        files: bl_appearance.zip